import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png";
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import dayjs from 'dayjs';

const AssignedTrainingReport = ({ departmentId, departmentName, skillsWithEmployees, docNo = 'TRN-ASSIGN-001', OriginDate, revNo = '1.0', revDate, onClose }) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null);
  const [previewOpen, setPreviewOpen] = useState(true);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    console.log("Skills With Employees Data:", skillsWithEmployees);
    generatePDF();
  }, []);

  const generatePDF = () => {
    const doc = new jsPDF({ format: "a4" });
    doc.setProperties({
      title: "Assigned Training Report",
      subject: "Department Training Assignment Report",
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Training, Assignment, Report, Department",
      creator: "Generated by AssignedTrainingReport",
    });

    let marginX = 10;
    let marginY = 10;
    let contentWidth = 190;

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, 277);

    // **Section 1: Logo & Company Name**
    doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    // **Section 2: Report Title (Centered)**
    let titleY = marginY + 3;
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text("Assigned Training Report", 105, titleY + 12, { align: "center" });

    // **Section 3: Right-Side Document Info**
    let rightX = marginX + 138;
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
    doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
    doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
    doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
    doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);

    // **Vertical Line separating Document Info**
    doc.line(marginX + 135, marginY, marginX + 135, marginY + 68);

    // **Section 4: Department Details**
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Department ID: ${departmentId || 'N/A'}`, marginX + 2, marginY + 39);
    doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
    doc.text(`Department Name: ${departmentName || 'N/A'}`, marginX + 2, marginY + 48);
    doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);
    
    // Calculate total employees assigned
    let totalEmployeesAssigned = 0;
    if (skillsWithEmployees) {
      Object.values(skillsWithEmployees).forEach(employees => {
        totalEmployeesAssigned += employees.length;
      });
    }
    
    doc.text(`Total Employees Assigned: ${totalEmployeesAssigned}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60, marginX + 135, marginY + 60);
    doc.text(`Generated Date: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 2, marginY + 65);
    doc.line(marginX, marginY + 68, contentWidth + 10, marginY + 68);

    // **Table Data: Training Assignments with all skills (including those without employees)**
    if (skillsWithEmployees && Object.keys(skillsWithEmployees).length > 0) {
      const tableData = [];
      let serialNo = 1;

      Object.keys(skillsWithEmployees).forEach((skillName) => {
        const employees = skillsWithEmployees[skillName] || [];
        const employeeCount = employees.length;

        if (employeeCount > 0) {
          // For skills with employees, add each employee as a row
          employees.forEach((emp, idx) => {
            tableData.push([
              serialNo.toString(),
              { content: skillName, styles: { fontSize: 10, fontStyle: 'normal' } },
              { content: emp.employeeName || 'N/A', styles: { fontSize: 10, fontStyle: 'normal' } },
              { content: employeeCount.toString(), styles: { fontSize: 10, fontStyle: 'normal', halign: 'center' } },
            ]);
            serialNo++;
          });
        } else {
          // For skills with no employees, add one row with employee count as 0
          tableData.push([
            serialNo.toString(),
            { content: skillName, styles: { fontSize: 10, fontStyle: 'normal' } },
            { content: 'No employees assigned', styles: { fontSize: 10, fontStyle: 'italic' } },
            { content: '0', styles: { fontSize: 10, fontStyle: 'normal', halign: 'center' } },
          ]);
          serialNo++;
        }
      });

      doc.autoTable({
        startY: 80,
        head: [["Sr No.", "Skill Name", "Employee Name", "No. of Employees"]],
        body: tableData,
        styles: {
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 10,
          textColor: [0, 0, 0],
          cellPadding: 4,
        },
        headStyles: {
          fillColor: [200, 200, 200],
          textColor: [0, 0, 0],
          fontStyle: "bold",
          fontSize: 11,
        },
        alternateRowStyles: { fillColor: false },
        columnStyles: {
          0: { halign: 'center', cellWidth: 15 },
          1: { halign: 'left', cellWidth: 60 },
          2: { halign: 'left', cellWidth: 85 },
          3: { halign: 'center', cellWidth: 30 },
        },
        theme: "grid",
        margin: { top: 20, left: 10, right: 10, bottom: 20 },
        tableLineWidth: 0.1,
      });

      // **Signatures**
      let signStartY = doc.autoTable.previous.finalY + 10;

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Department Head Sign:          ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("Manager Sign:                  ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("HR Sign:                       ", marginX + 2, signStartY);
    } else {
      doc.text("No training data found", 10, 90);
    }

    // Generate the PDF data URL
    const pdfData = doc.output('datauristring');
    setPdfDataUrl(pdfData);
    setLoading(false);
    setPreviewOpen(true);
  };

  const handleClosePreview = () => {
    console.log('Closing assigned training report modal');
    setPreviewOpen(false);
    setPdfDataUrl(null);
    if (onClose) {
      onClose();
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ format: "a4" });
    doc.setProperties({
      title: "Assigned Training Report",
    });

    let marginX = 10;
    let marginY = 10;
    let contentWidth = 190;

    doc.rect(marginX, marginY, contentWidth, 277);
    doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    let titleY = marginY + 3;
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text("Assigned Training Report", 105, titleY + 12, { align: "center" });

    let rightX = marginX + 138;
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
    doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
    doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
    doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
    doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);
    doc.line(marginX + 135, marginY, marginX + 135, marginY + 68);

    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Department ID: ${departmentId || 'N/A'}`, marginX + 2, marginY + 39);
    doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
    doc.text(`Department Name: ${departmentName || 'N/A'}`, marginX + 2, marginY + 48);
    doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);

    let totalEmployeesAssigned = 0;
    if (skillsWithEmployees) {
      Object.values(skillsWithEmployees).forEach(employees => {
        totalEmployeesAssigned += employees.length;
      });
    }

    doc.text(`Total Employees Assigned: ${totalEmployeesAssigned}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60, marginX + 135, marginY + 60);
    doc.text(`Generated Date: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 2, marginY + 65);
    doc.line(marginX, marginY + 68, contentWidth + 10, marginY + 68);

    if (skillsWithEmployees && Object.keys(skillsWithEmployees).length > 0) {
      const tableData = [];
      let serialNo = 1;

      Object.keys(skillsWithEmployees).forEach((skillName) => {
        const employees = skillsWithEmployees[skillName] || [];
        const employeeCount = employees.length;

        if (employeeCount > 0) {
          // For skills with employees, add each employee as a row
          employees.forEach((emp, idx) => {
            tableData.push([
              serialNo.toString(),
              { content: skillName, styles: { fontSize: 10, fontStyle: 'normal' } },
              { content: emp.employeeName || 'N/A', styles: { fontSize: 10, fontStyle: 'normal' } },
              { content: employeeCount.toString(), styles: { fontSize: 10, fontStyle: 'normal', halign: 'center' } },
            ]);
            serialNo++;
          });
        } else {
          // For skills with no employees, add one row with employee count as 0
          tableData.push([
            serialNo.toString(),
            { content: skillName, styles: { fontSize: 10, fontStyle: 'normal' } },
            { content: 'No employees assigned', styles: { fontSize: 10, fontStyle: 'italic' } },
            { content: '0', styles: { fontSize: 10, fontStyle: 'normal', halign: 'center' } },
          ]);
          serialNo++;
        }
      });

      doc.autoTable({
        startY: 80,
        head: [["Sr No.", "Skill Name", "Employee Name", "No. of Employees"]],
        body: tableData,
        styles: {
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 10,
          textColor: [0, 0, 0],
          cellPadding: 4,
        },
        headStyles: {
          fillColor: [200, 200, 200],
          textColor: [0, 0, 0],
          fontStyle: "bold",
          fontSize: 11,
        },
        alternateRowStyles: { fillColor: false },
        columnStyles: {
          0: { halign: 'center', cellWidth: 15 },
          1: { halign: 'left', cellWidth: 60 },
          2: { halign: 'left', cellWidth: 85 },
          3: { halign: 'center', cellWidth: 30 },
        },
        theme: "grid",
        margin: { top: 20, left: 10, right: 10, bottom: 20 },
        tableLineWidth: 0.1,
      });

      let signStartY = doc.autoTable.previous.finalY + 10;
      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Department Head Sign:          ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("Manager Sign:                  ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("HR Sign:                       ", marginX + 2, signStartY);
    }

    doc.save(`Assigned_Training_Report_${departmentId}_${dayjs().format('YYYY-MM-DD')}.pdf`);
  };

  return (
    <div>
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
      >
        <Box sx={{ width: "85%", margin: "auto", mt: 5, backgroundColor: "white", padding: 2, borderRadius: 2, maxHeight: '90vh', overflow: 'auto' }}>
          <Typography variant="h6" sx={{ mb: 2, fontWeight: 'bold' }}>
            Assigned Training Report - PDF Preview
          </Typography>

          {pdfDataUrl ? (
            <iframe
              src={pdfDataUrl}
              width="100%"
              height="600px"
              style={{ border: '1px solid #ddd', borderRadius: '4px' }}
              title="PDF Preview"
            />
          ) : (
            <Typography variant="body1">Loading PDF preview...</Typography>
          )}

          <div style={{ marginTop: '20px', display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <Button 
              onClick={handleDownloadPDF} 
              variant="contained" 
              color="primary"
            >
              Download PDF
            </Button>
            <Button 
              onClick={handleClosePreview} 
              variant="outlined" 
              color="secondary"
            >
              Close Preview
            </Button>
          </div>
        </Box>
      </Modal>
    </div>
  );
};

export default AssignedTrainingReport;
