import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png";
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import dayjs from 'dayjs';

const CumulativeAttendanceGenerator = ({ reportTitle, docNo, OriginDate, revNo, revDate, trainerName, trainingTitle, location, startTrainingDate, endTrainingDate, tableHeaders, tableData, employeeAttendanceData, onClose }) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null);
  const [previewOpen, setPreviewOpen] = useState(true);
  const [loading, setLoading] = useState(true);

  // Guard against invalid props
  const safeEmployeeData = Array.isArray(employeeAttendanceData) ? employeeAttendanceData : [];

  useEffect(() => {
    if (safeEmployeeData.length > 0) {
      console.log("Cumulative Attendance Data:", safeEmployeeData);
      generatePDF();
    }
  }, [employeeAttendanceData]);

  const createDoc = () => {
    // A3 format landscape for better session columns fit
    const doc = new jsPDF({ 
      format: "a3",
      orientation: "landscape"
    });
    
    doc.setProperties({
      title: reportTitle,
      subject: "Cumulative Attendance Report",
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Training, Attendance, Cumulative, Report",
      creator: "Generated by CumulativeAttendanceGenerator",
    });

    const pageWidth = doc.internal.pageSize.getWidth();  // 420mm for A3 landscape
    const pageHeight = doc.internal.pageSize.getHeight(); // 297mm for A3 landscape
    const marginX = 10;
    const marginY = 10;
    const contentWidth = pageWidth - (marginX * 2);
    const contentHeight = pageHeight - (marginY * 2);

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, contentHeight);

    // **Section 1: Logo & Company Name**
    try {
      doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    } catch (e) {
      console.warn("Logo image failed to load:", e);
    }
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    // **Section 2: Report Title (Centered)**
    doc.setFontSize(18).setFont("helvetica", "bold");
    doc.text(reportTitle || "Cumulative Attendance Report", pageWidth / 2, marginY + 15, { align: "center" });

    // **Section 3: Right-Side Document Info**
    let rightX = pageWidth - marginX - 60;
    doc.setFontSize(10).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo || 'N/A'}`, rightX, marginY + 5);
    doc.line(rightX - 3, marginY + 8, pageWidth - marginX, marginY + 8);
    doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
    doc.line(rightX - 3, marginY + 16, pageWidth - marginX, marginY + 16);
    doc.text(`Rev No.: ${revNo || '1.0'}`, rightX, marginY + 21);
    doc.line(rightX - 3, marginY + 24, pageWidth - marginX, marginY + 24);
    doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
    doc.line(rightX - 3, marginY + 33, pageWidth - marginX, marginY + 33);

    // Vertical line for right section
    doc.line(rightX - 3, marginY, rightX - 3, marginY + 60);

    // **Section 4: Training Details**
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Training Title: ${trainingTitle || 'N/A'}`, marginX + 2, marginY + 39);
    doc.line(marginX, marginY + 42, rightX - 3, marginY + 42);
    doc.text(`Trainer Name: ${trainerName || 'N/A'}`, marginX + 2, marginY + 48);
    doc.text(`Location: ${location || 'N/A'}`, marginX + 150, marginY + 48);
    doc.line(marginX, marginY + 51, rightX - 3, marginY + 51);
    doc.text(`Training Period: ${startTrainingDate || 'N/A'} To ${endTrainingDate || 'N/A'}`, marginX + 2, marginY + 57);
    doc.text(`Generated: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 150, marginY + 57);
    doc.line(marginX, marginY + 60, pageWidth - marginX, marginY + 60);

    // **Legend for P/A**
    const legendStartX = marginX + 300;
    const legendY = marginY + 48;
    doc.setFontSize(9).setFont("helvetica", "bold");
    doc.text("Legend:", legendStartX, legendY);
    
    // P - Present
    doc.setFillColor(144, 238, 144); // Light green
    doc.rect(legendStartX + 18, legendY - 3, 8, 5, 'F');
    doc.setDrawColor(0, 100, 0);
    doc.rect(legendStartX + 18, legendY - 3, 8, 5);
    doc.setFontSize(8).setFont("helvetica", "bold");
    doc.setTextColor(0, 100, 0);
    doc.text("P", legendStartX + 20, legendY);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text("= Present", legendStartX + 28, legendY);
    
    // A - Absent
    doc.setFillColor(255, 200, 200); // Light red
    doc.rect(legendStartX + 55, legendY - 3, 8, 5, 'F');
    doc.setDrawColor(200, 0, 0);
    doc.rect(legendStartX + 55, legendY - 3, 8, 5);
    doc.setFontSize(8).setFont("helvetica", "bold");
    doc.setTextColor(200, 0, 0);
    doc.text("A", legendStartX + 57, legendY);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text("= Absent", legendStartX + 65, legendY);

    // **Build Table Data**
    if (safeEmployeeData.length > 0) {
      // Get all sessions from first employee
      const allSessions = safeEmployeeData[0]?.sessions || [];
      const totalSessions = allSessions.length;

      // Calculate column widths - ensure minimum width for readability
      const fixedColumnsWidth = 15 + 55 + 25 + 32; // Sr No + Name + Total + %
      const availableWidthForSessions = contentWidth - fixedColumnsWidth - 10;
      const minSessionColumnWidth = 22; // Minimum width to show P/A properly
      const maxSessionsPerPage = Math.max(1, Math.floor(availableWidthForSessions / minSessionColumnWidth));

      // Split sessions into chunks if too many
      const sessionChunks = [];
      for (let i = 0; i < totalSessions; i += maxSessionsPerPage) {
        sessionChunks.push({
          startIndex: i,
          endIndex: Math.min(i + maxSessionsPerPage, totalSessions),
          sessions: allSessions.slice(i, i + maxSessionsPerPage)
        });
      }

      // If no sessions, create one empty chunk
      if (sessionChunks.length === 0) {
        sessionChunks.push({ startIndex: 0, endIndex: 0, sessions: [] });
      }

      let currentPage = 1;
      const totalPages = sessionChunks.length;

      // Custom cell styling for P (Green) and A (Red)
      const didDrawCell = (data) => {
        const cell = data.cell;
        const text = cell.text[0];
        
        if (data.section === 'body' && (text === 'P' || text === 'A')) {
          if (text === 'P') {
            data.doc.setFillColor(144, 238, 144); // Light green
            data.doc.rect(cell.x, cell.y, cell.width, cell.height, 'F');
            data.doc.setTextColor(0, 100, 0); // Dark green text
            data.doc.setFont("helvetica", "bold");
            data.doc.text('P', cell.x + cell.width / 2, cell.y + cell.height / 2 + 1, { align: 'center' });
          } else {
            data.doc.setFillColor(255, 200, 200); // Light red
            data.doc.rect(cell.x, cell.y, cell.width, cell.height, 'F');
            data.doc.setTextColor(200, 0, 0); // Dark red text
            data.doc.setFont("helvetica", "bold");
            data.doc.text('A', cell.x + cell.width / 2, cell.y + cell.height / 2 + 1, { align: 'center' });
          }
          // Draw cell border
          data.doc.setDrawColor(0, 0, 0);
          data.doc.rect(cell.x, cell.y, cell.width, cell.height);
          data.doc.setTextColor(0, 0, 0);
        }
      };

      // Generate table for each session chunk
      sessionChunks.forEach((chunk, chunkIndex) => {
        if (chunkIndex > 0) {
          doc.addPage();
          currentPage++;
          
          // Draw header for continuation pages
          doc.setFontSize(12).setFont("helvetica", "bold");
          doc.text(`Cumulative Attendance Report - ${trainingTitle} (Page ${currentPage}/${totalPages})`, pageWidth / 2, 15, { align: "center" });
          
          // Draw session range info
          doc.setFontSize(10).setFont("helvetica", "normal");
          doc.text(`Sessions ${chunk.startIndex + 1} - ${chunk.endIndex} of ${totalSessions}`, pageWidth / 2, 22, { align: "center" });
        }

        const sessionsInChunk = chunk.sessions.length;

        // Build headers: Sr No, Employee Name, Total, Attendance %, ...Sessions
        const headers = ["Sr No.", "Employee Name", "Total", "Attend %"];
        chunk.sessions.forEach((session, idx) => {
          const sessionLabel = session.sessionName || `S${chunk.startIndex + idx + 1}`;
          // Truncate long session names to fit column
          const maxLen = 10;
          const truncatedName = sessionLabel.length > maxLen 
            ? sessionLabel.substring(0, maxLen - 2) + '..' 
            : sessionLabel;
          headers.push(truncatedName);
        });

        // Build body rows
        const bodyData = safeEmployeeData.map((employee, index) => {
          const row = [
            (index + 1).toString(),
            employee.employeeName || 'N/A',
            `${employee.attended}/${employee.totalSessions}`,
            employee.attendancePercentage ? `${employee.attendancePercentage.toFixed(1)}%` : '0%',
          ];

          // Add attendance status for sessions in this chunk
          if (employee.sessions) {
            for (let i = chunk.startIndex; i < chunk.endIndex; i++) {
              const session = employee.sessions[i];
              row.push(session?.attendanceStatus === 1 ? 'P' : 'A');
            }
          }

          return row;
        });

        // Calculate column widths for this chunk - distribute remaining space evenly
        const sessionColumnWidth = sessionsInChunk > 0 
          ? Math.max(minSessionColumnWidth, availableWidthForSessions / sessionsInChunk)
          : minSessionColumnWidth;

        const columnStyles = {
          0: { halign: 'center', cellWidth: 15 },   // Sr No
          1: { halign: 'left', cellWidth: 55 },     // Employee Name
          2: { halign: 'center', cellWidth: 25 },   // Total
          3: { halign: 'center', cellWidth: 32 },   // Attendance %
        };

        // Add column styles for each session
        for (let i = 0; i < sessionsInChunk; i++) {
          columnStyles[i + 4] = { halign: 'center', cellWidth: sessionColumnWidth };
        }

        const tableStartY = chunkIndex === 0 ? 70 : 30;

        doc.autoTable({
          startY: tableStartY,
          head: [headers],
          body: bodyData,
          styles: {
            lineWidth: 0.1,
            lineColor: [0, 0, 0],
            fontSize: 8,
            textColor: [0, 0, 0],
            cellPadding: 2,
            minCellHeight: 12,
            valign: 'middle',
          },
          headStyles: {
            fillColor: [70, 130, 180],  // Steel blue
            textColor: [255, 255, 255],
            fontStyle: "bold",
            fontSize: 7,
            halign: 'center',
            valign: 'middle',
            minCellHeight: 16,
            cellPadding: 1,
          },
          alternateRowStyles: { fillColor: [248, 248, 248] },
          columnStyles: columnStyles,
          theme: "grid",
          margin: { top: tableStartY, left: marginX, right: marginX, bottom: 30 },
          tableLineWidth: 0.1,
          didDrawCell: didDrawCell,
          willDrawPage: (data) => {
            // Add header on new pages due to row overflow
            if (data.pageNumber > 1 && chunkIndex === 0) {
              doc.setFontSize(12).setFont("helvetica", "bold");
              doc.text(`Cumulative Attendance Report - ${trainingTitle} (Continued)`, pageWidth / 2, 15, { align: "center" });
            }
          },
          showHead: 'everyPage',
          rowPageBreak: 'avoid',
        });
      });

      // **Signatures Section** (only on last page)
      const finalY = doc.autoTable.previous.finalY;
      let signStartY = finalY + 15;

      if (signStartY + 40 > pageHeight - marginY) {
        doc.addPage();
        signStartY = 30;
      }

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Sign of Trainer: ____________________", marginX + 10, signStartY);
      doc.text("Sign of HR: ____________________", marginX + 150, signStartY);
      doc.text("Sign of HOD: ____________________", marginX + 290, signStartY);

    } else {
      doc.setFontSize(12).setFont("helvetica", "normal");
      doc.text("No attendance records found.", pageWidth / 2, 100, { align: "center" });
    }

    return doc;
  };

  const generatePDF = () => {
    try {
      const doc = createDoc();
      const pdfData = doc.output('datauristring');
      setPdfDataUrl(pdfData);
      setLoading(false);
      setPreviewOpen(true);
    } catch (error) {
      console.error("Error generating PDF:", error);
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = createDoc();
      doc.save(`Cumulative_Attendance_${trainingTitle}_${dayjs().format('DD_MM_YYYY')}.pdf`);
    } catch (error) {
      console.error("Error downloading PDF:", error);
    }
  };

  const handleClosePreview = () => {
    setPreviewOpen(false);
    onClose?.();
  };

  if (loading) {
    return (
      <Modal open={true}>
        <Box sx={{ 
          width: "100%", 
          height: "100%", 
          display: 'flex', 
          alignItems: 'center', 
          justifyContent: 'center', 
          backgroundColor: "rgba(0,0,0,0.7)" 
        }}>
          <Typography sx={{ color: 'white', fontSize: 20 }}>Generating Report...</Typography>
        </Box>
      </Modal>
    );
  }

  return (
    <div>
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
      >
        <Box sx={{ 
          width: "98%", 
          maxWidth: "1800px",
          margin: "auto", 
          mt: 1, 
          backgroundColor: "white", 
          padding: 2, 
          borderRadius: 2, 
          height: '98vh', 
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column'
        }}>
          <Typography variant="h6" sx={{ mb: 1, fontWeight: 'bold', flexShrink: 0 }}>
            Cumulative Attendance Report - PDF Preview (A3 Landscape)
          </Typography>

          {pdfDataUrl ? (
            <>
              {/* Scrollable container for A3 preview with zoom */}
              <Box sx={{ 
                flex: 1,
                overflow: 'auto', 
                border: '1px solid #ddd', 
                borderRadius: '4px',
                mb: 2,
                minHeight: '600px',
                maxHeight: 'calc(98vh - 120px)',
                '& iframe': {
                  minWidth: '1400px',
                  minHeight: '900px',
                }
              }}>
                <iframe
                  src={pdfDataUrl}
                  width="100%"
                  height="100%"
                  style={{ 
                    border: 'none',
                    minWidth: '1400px',
                    minHeight: '900px',
                  }}
                  title="PDF Preview"
                />
              </Box>
              
              <Box sx={{ display: 'flex', gap: 2, justifyContent: 'flex-end', flexShrink: 0 }}>
                <Typography variant="body2" sx={{ alignSelf: 'center', color: 'gray', mr: 'auto' }}>
                  💡 Tip: Scroll horizontally and vertically to view the full A3 document
                </Typography>
                <Button variant="contained" color="primary" onClick={handleDownloadPDF}>
                  Download PDF
                </Button>
                <Button variant="outlined" color="secondary" onClick={handleClosePreview}>
                  Close
                </Button>
              </Box>
            </>
          ) : (
            <Typography>Failed to generate PDF</Typography>
          )}
        </Box>
      </Modal>
    </div>
  );
};

export default CumulativeAttendanceGenerator;
