import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png"; // Ensure PNG format is used
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import { Document, Page, pdfjs } from 'react-pdf';
import dayjs from 'dayjs';

// Set workerSrc for React-PDF
pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

const ReportGenerator = ({ reportTitle, docNo, OriginDate,creators, revNo, revDate, trainerName, trainingTitle, location, sessionDate = '', startTrainingDate, endTrainingDate, tableHeaders, tableData }) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null); // Store generated PDF data URL
  const [previewOpen, setPreviewOpen] = useState(false); // State to control modal visibility
  const [loading, setLoading] = useState(true); // For loading state

  useEffect(() => {
    // Generate PDF preview on component mount
    console.log("header", tableHeaders);
    generatePDF();
  }, []);

  const generatePDF = () => {
    const doc = new jsPDF({ format: "a4" });
    doc.setProperties({
      title: reportTitle,  // This sets the correct title
      subject: "Training Attendance Report",      //should also be dynamic?
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Training, Attendance, Report",   //are these needed? Also should they be dynamic
      creator: "Generated by ReportGenerator",    //do you need login emp name over here?
  });


    let marginX = 10;
    let marginY = 10;
    let contentWidth = 190; // Full width with margins

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, 277); // A4 page height is 297mm

    // **Section 1: Logo & Company Name (Box Outline for Section & Elements)**
    doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    doc.line(marginX , marginY + 25 , marginX + 57, marginY + 25); // Company logo Box
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX , marginY + 33 , marginX + 135 , marginY + 33); // Horizontal line after Company Name
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33); // Vertical line after logo

    // **Section 2: Report Title (Centered, Box Outline)**
    let titleY = marginY + 3;
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text(reportTitle, 105, titleY + 12, { align: "center" });

    // **Section 3: Right-Side Document Info (Box Outline)**
    let rightX = marginX + 138;
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135 , marginY + 8 , contentWidth + 10 , marginY + 8); // Line after Doc No.
    doc.text(`Origin Date: ${OriginDate}`, rightX, marginY + 13);
    doc.line(marginX + 135 , marginY + 16 , contentWidth + 10 , marginY + 16); // Line after Origin Date
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135 , marginY + 24 , contentWidth + 10 , marginY + 24); // Line after Rev No.
    doc.text(`Rev Date: ${revDate}`, rightX, marginY + 30);
    doc.line(marginX + 135 , marginY + 33 ,contentWidth + 10 , marginY + 33); // Line after Rev Date
    doc.text(location, rightX, marginY + 39);
    doc.line(marginX + 135 , marginY + 43 , contentWidth + 10 , marginY + 43); // Line after Name of Trainer

    // **Vertical Line separating Document Info**
    doc.line(marginX + 135 , marginY, marginX + 135, marginY + 68); // Vertical line separating info

    // **Section 4: Training Details (Box Outline)**
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text("Training Title:", marginX + 2, marginY + 39);
    doc.text(trainingTitle, marginX + 50, marginY + 39);
    doc.line(marginX, marginY + 43 , marginX + 135 , marginY + 43); // Line after each entry
    doc.text("Trainer Name:", marginX + 2, marginY + 48);
    doc.text(trainerName, marginX + 50, marginY + 48);
    doc.line(marginX, marginY + 51 , marginX + 135 , marginY + 51); // Line after each entry
    doc.text(`Training From: ${startTrainingDate} To: ${endTrainingDate}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60 , contentWidth + 10 , marginY + 60); // Line after each entry

    // **Table Data**
    if (tableData && tableData.length > 0) {  
      const tableDataWithSerialNo = tableData.map((item, index) => ({
        ...item,
        srNo: index + 1, // Add serial number starting from 1
      }));

      // Helper function to format employee data with count and names
      const formatEmployeeInfo = (count, names) => {
        if (!names || names === 'N/A') {
          return count?.toString() || '0';
        }
        // Truncate long names list for better readability
        const namesList = names.split(', ').slice(0, 3).join(', ');
        const remaining = names.split(', ').length - 3;
        const suffix = remaining > 0 ? ` +${remaining}` : '';
        return `${count}\n${namesList}${suffix}`;
      };

      doc.autoTable({
        startY: 65,
        head: [["Sr No.", "Session Name", "Date", "Time", "Expected", "Attended", "Absent"]],  
        body: tableDataWithSerialNo.map(item => [
          item.srNo.toString(),
          item.sessionName || '',
          item.sessionDate || '',
          item.sessionTime || '',
          formatEmployeeInfo(item.expectedEmployees, item.expectedEmployeeNames),
          formatEmployeeInfo(item.attendedEmployees, item.attendedEmployeeNames),
          formatEmployeeInfo(item.absentEmployees, item.absentEmployeeNames),
        ]),
        styles: { 
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 7,
          textColor: [0, 0, 0],
          fontStyle: "normal",
          cellPadding: 2.5,
          valign: 'top',
          halign: 'left',
          overflow: 'linebreak',
        },
        headStyles: { 
          fillColor: [200, 200, 200],
          textColor: [0, 0, 0],
          fontStyle: "bold",
          fontSize: 8,
          halign: 'center',
          valign: 'middle',
        },
        alternateRowStyles: { fillColor: false },
        columnStyles: {
          0: { halign: 'center', cellWidth: 10 },
          1: { halign: 'left', cellWidth: 22 },
          2: { halign: 'center', cellWidth: 15 },
          3: { halign: 'center', cellWidth: 16 },
          4: { halign: 'left', cellWidth: 32 },
          5: { halign: 'left', cellWidth: 32 },
          6: { halign: 'left', cellWidth: 32 },
        },
        theme: "grid",
        margin: { top: 15, left: 10, right: 10, bottom: 20 },
        tableLineWidth: 0.1,
        didDrawPage: (data) => {
          // Optional: Handle page breaks if needed
        },
      });      

      // **Signatures**
      let signStartY = doc.autoTable.previous.finalY + 10; // Positioning below the table

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Sign of Trainer:                  ", marginX + 2, signStartY);
      signStartY += 15; // Increase Y position for next sign
      doc.text("Sign of HR:                       ", marginX + 2, signStartY);
      signStartY += 15; // Increase Y position for next sign
      doc.text("Sign of HOD:                      ", marginX + 2, signStartY);
    } else {
      doc.text("No records found", 10, 90);
    }

    // Generate the PDF data URL
    const pdfData = doc.output('datauristring');  // Output as a Data URL
    setPdfDataUrl(pdfData);  // Set the generated PDF data URL for preview
    setLoading(false); // Set loading to false once the PDF is ready
    setPreviewOpen(true);  // Open the modal for preview
  };

  // Handle the modal open and close actions
  const handleClosePreview = () => {
    setPreviewOpen(false); // Close the modal
    setPdfDataUrl(null);  // Reset PDF preview data (optional)
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ format: "a4" });
    // Reuse the same generatePDF logic
    const pdfData = doc.output('blob');
    const url = URL.createObjectURL(pdfData);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Training_Report_${trainingTitle}_${dayjs().format('DD_MM_YYYY')}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      {/* Preview Modal */}
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
        aria-describedby="pdf-preview-description"
      >
        <Box sx={{ width: "85%", margin: "auto", mt: 5, backgroundColor: "white", padding: 2 }}>
          <Typography variant="h6" sx={{ mb: 1 }}>
            PDF Preview
          </Typography>

          {pdfDataUrl ? (
            <iframe
              src={pdfDataUrl}
              width="100%"
              height="500px"
              style={{ border: 'none' }}
              title="PDF Preview"
            />
          ) : (
            <Typography variant="body1">Loading PDF preview...</Typography>
          )}

          <div style={{ marginTop: '20px', display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <Button 
              onClick={handleDownloadPDF} 
              variant="contained" 
              color="primary"
            >
              Download PDF
            </Button>
            <Button 
              onClick={handleClosePreview} 
              variant="outlined" 
              color="secondary"
            >
              Close Preview
            </Button>
          </div>
        </Box>
      </Modal>
    </div>
  );
};

export default ReportGenerator;
