import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png"; // Ensure PNG format is used
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import { Document, Page, pdfjs } from 'react-pdf';
import dayjs from 'dayjs';

// Set workerSrc for React-PDF
pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

const ReportGenerator = ({ reportTitle, docNo, OriginDate,creators, revNo, revDate, trainerName, trainingTitle, location, sessionDate = '', startTrainingDate, endTrainingDate, tableHeaders, tableData, onClose }) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null); // Store generated PDF data URL
  const [previewOpen, setPreviewOpen] = useState(true); // Start with preview open
  const [loading, setLoading] = useState(true); // For loading state

  useEffect(() => {
    // Generate PDF preview on component mount
    if (tableData && tableData.length > 0) {
      console.log("header", tableHeaders);
      generatePDF();
    }
  }, [tableData]);

  // **Extract single document creation function**
  const createDoc = () => {
    const doc = new jsPDF({ format: "a4" });
    doc.setProperties({
      title: reportTitle,
      subject: "Training Attendance Report",
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Training, Attendance, Report",
      creator: "Generated by ReportGenerator",
    });

    let marginX = 10;
    let marginY = 10;
    let contentWidth = 190; // Full width with margins

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, 277);

    // **Section 1: Logo & Company Name**
    doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    // **Section 2: Report Title**
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text(reportTitle, 105, marginY + 15, { align: "center" });

    // **Section 3: Right-Side Document Info**
    let rightX = marginX + 138;
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
    doc.text(`Origin Date: ${OriginDate}`, rightX, marginY + 13);
    doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
    doc.text(`Rev Date: ${revDate}`, rightX, marginY + 30);
    doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);
    doc.text(location, rightX, marginY + 39);
    doc.line(marginX + 135, marginY + 43, contentWidth + 10, marginY + 43);

    // **Vertical Line separating Document Info**
    doc.line(marginX + 135, marginY, marginX + 135, marginY + 68);

    // **Section 4: Training Details**
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text("Training Title:", marginX + 2, marginY + 39);
    doc.text(trainingTitle, marginX + 50, marginY + 39);
    doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
    doc.text("Trainer Name:", marginX + 2, marginY + 48);
    doc.text(trainerName, marginX + 50, marginY + 48);
    doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);
    doc.text(`Training From: ${startTrainingDate} To: ${endTrainingDate}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60, contentWidth + 10, marginY + 60);

    // **Table Data**
    if (tableData && tableData.length > 0) {
      let currentStartY = 75;

      // Calculate available width for table
      const pageWidth = doc.internal.pageSize.getWidth();
      const leftMargin = 10;
      const rightMargin = 10;
      const availableWidth = pageWidth - leftMargin - rightMargin;

      // Define desired column widths (total should be <= availableWidth)
      const desiredWidths = {
        0: 12,   // Sr No
        1: 30,   // Session Name
        2: 22,   // Date
        3: 24,   // Time
        4: 34,   // Expected
        5: 34,   // Attended
        6: 34,   // Absent
      };

      const totalDesiredWidth = Object.values(desiredWidths).reduce((a, b) => a + b, 0);

      // Scale widths to fit available width exactly
      const scaleFactor = availableWidth / totalDesiredWidth;
      
      const columnStyles = {};
      Object.entries(desiredWidths).forEach(([key, width]) => {
        columnStyles[key] = { 
          halign: ['center', 'left', 'center', 'center', 'left', 'left', 'left'][parseInt(key)],
          cellWidth: width * scaleFactor 
        };
      });

      // Helper function to format employee data with count and names
      const formatEmployeeInfo = (count, names) => {
        if (!names || names === 'N/A') {
          return count?.toString() || '0';
        }
        const namesList = names.split(', ').slice(0, 3).join(', ');
        const remaining = names.split(', ').length - 3;
        const suffix = remaining > 0 ? ` +${remaining} more` : '';
        return `${count}\n${namesList}${suffix}`;
      };

      // Build all table rows at once
      const allTableRows = tableData.map((session, index) => [
        (index + 1).toString(),
        session.sessionName || '',
        session.sessionDate || '',
        session.sessionTime || '',
        formatEmployeeInfo(session.expectedEmployees, session.expectedEmployeeNames),
        formatEmployeeInfo(session.attendedEmployees, session.attendedEmployeeNames),
        formatEmployeeInfo(session.absentEmployees, session.absentEmployeeNames),
      ]);

      // Create single table with all sessions
      doc.autoTable({
        startY: currentStartY,
        head: [["Sr No.", "Session Name", "Date", "Time", "Expected", "Attended", "Absent"]],
        body: allTableRows,
        styles: {
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 9,
          textColor: [0, 0, 0],
          fontStyle: "normal",
          cellPadding: 4,
          valign: 'middle',
          halign: 'left',
          overflow: 'linebreak',
          minCellHeight: 12,
        },
        headStyles: {
          fillColor: [70, 130, 180],  // Steel blue header
          textColor: [255, 255, 255],
          fontStyle: "bold",
          fontSize: 10,
          halign: 'center',
          valign: 'middle',
          minCellHeight: 14,
        },
        alternateRowStyles: { fillColor: [245, 245, 245] },
        columnStyles: columnStyles,
        theme: "grid",
        margin: { left: leftMargin, right: rightMargin, top: 25, bottom: 20 },
        tableLineWidth: 0.1,
        tableWidth: availableWidth,
        // Handle page breaks properly
        willDrawPage: (data) => {
          // Add header on new pages before the table is drawn
          if (data.pageNumber > 1) {
            doc.setFontSize(10).setFont("helvetica", "bold");
            doc.text(`${reportTitle} - Page ${data.pageNumber}`, pageWidth / 2, 12, { align: "center" });
            doc.setFontSize(9).setFont("helvetica", "normal");
            doc.text(`Training: ${trainingTitle} | Trainer: ${trainerName}`, pageWidth / 2, 18, { align: "center" });
          }
        },
        // Ensure rows don't break awkwardly
        rowPageBreak: 'avoid',
        showHead: 'everyPage',
      });

      // Get the final Y position after the table
      const finalY = doc.autoTable.previous.finalY;

      // **Signatures Section**
      let signStartY = finalY + 20;
      const pageHeight = doc.internal.pageSize.getHeight();

      // Check if signatures fit on current page (need about 60px for signatures)
      if (signStartY + 50 > pageHeight - 15) {
        doc.addPage();
        signStartY = 30;
      }

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Sign of Trainer: ____________________", marginX + 5, signStartY);
      doc.text("Sign of HR: ____________________", marginX + 5, signStartY + 18);
      doc.text("Sign of HOD: ____________________", marginX + 5, signStartY + 36);
    } else {
      doc.setFontSize(12).setFont("helvetica", "normal");
      doc.text("No session records found for this training.", 105, 90, { align: "center" });
    }

    return doc;
  };

  const generatePDF = () => {
    const doc = createDoc();
    const pdfData = doc.output('datauristring');
    setPdfDataUrl(pdfData);
    setLoading(false);
    setPreviewOpen(true);
  };

  // Handle the modal open and close actions
  const handleClosePreview = () => {
    setPreviewOpen(false); // Close the modal
    setPdfDataUrl(null);  // Reset PDF preview data (optional)
    // Notify parent to close the ReportGenerator
    if (onClose) {
      onClose();
    }
  };

  const handleDownloadPDF = () => {
    const doc = createDoc();
    doc.save(`Training_Report_${trainingTitle}_${dayjs().format('DD_MM_YYYY')}.pdf`);
  };

  return (
    <div>
      {/* Preview Modal */}
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
        aria-describedby="pdf-preview-description"
      >
        <Box sx={{ width: "85%", margin: "auto", mt: 5, backgroundColor: "white", padding: 2 }}>
          <Typography variant="h6" sx={{ mb: 1 }}>
            PDF Preview
          </Typography>

          {pdfDataUrl ? (
            <iframe
              src={pdfDataUrl}
              width="100%"
              height="500px"
              style={{ border: 'none' }}
              title="PDF Preview"
            />
          ) : (
            <Typography variant="body1">Loading PDF preview...</Typography>
          )}

          <div style={{ marginTop: '20px', display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <Button 
              onClick={handleDownloadPDF} 
              variant="contained" 
              color="primary"
            >
              Download PDF
            </Button>
            <Button 
              onClick={handleClosePreview} 
              variant="outlined" 
              color="secondary"
            >
              Close Preview
            </Button>
          </div>
        </Box>
      </Modal>
    </div>
  );
};

export default ReportGenerator;
