import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png";
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import dayjs from 'dayjs';

const SessionAttendanceReport = ({ 
  trainingTitle, 
  trainerName, 
  sessionName,
  sessionDate,
  sessionTime,
  startTrainingDate, 
  endTrainingDate, 
  location,
  attendanceData, 
  onClose,
  docNo = 'SESSION-ATT-001',
  OriginDate,
  revNo = '1.0',
  revDate
}) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null);
  const [previewOpen, setPreviewOpen] = useState(true);
  const [loading, setLoading] = useState(true);

  // Guard against invalid props
  const safeAttendanceData = Array.isArray(attendanceData) ? attendanceData : [];

  useEffect(() => {
    if (safeAttendanceData.length > 0) {
      console.log("Session Attendance Data:", safeAttendanceData);
      generatePDF();
    } else {
      setLoading(false);
    }
  }, [attendanceData]);

  const createDoc = () => {
    // A4 format portrait
    const doc = new jsPDF({ 
      format: "a4",
      orientation: "portrait"
    });
    
    doc.setProperties({
      title: "Session Attendance Report",
      subject: "Training Session Attendance Report",
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Training, Session, Attendance, Report",
      creator: "Generated by SessionAttendanceReport",
    });

    const pageWidth = doc.internal.pageSize.getWidth();  // 210mm for A4
    const pageHeight = doc.internal.pageSize.getHeight(); // 297mm for A4
    const marginX = 10;
    const marginY = 10;
    const contentWidth = pageWidth - (marginX * 2);

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, pageHeight - (marginY * 2));

    // **Section 1: Logo & Company Name**
    try {
      doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    } catch (e) {
      console.warn("Logo image failed to load:", e);
    }
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    // **Section 2: Report Title (Centered)**
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text("Session Attendance Report", pageWidth / 2, marginY + 15, { align: "center" });

    // **Section 3: Right-Side Document Info**
    let rightX = marginX + 138;
    doc.setFontSize(10).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135, marginY + 8, contentWidth + marginX, marginY + 8);
    doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
    doc.line(marginX + 135, marginY + 16, contentWidth + marginX, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135, marginY + 24, contentWidth + marginX, marginY + 24);
    doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
    doc.line(marginX + 135, marginY + 33, contentWidth + marginX, marginY + 33);

    // **Vertical Line separating Document Info**
    doc.line(marginX + 135, marginY, marginX + 135, marginY + 80);

    // **Section 4: Training & Session Details**
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Training Title: ${trainingTitle || 'N/A'}`, marginX + 2, marginY + 39);
    doc.line(marginX, marginY + 42, marginX + 135, marginY + 42);
    
    doc.text(`Trainer Name: ${trainerName || 'N/A'}`, marginX + 2, marginY + 48);
    doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);
    
    doc.text(`Training Period: ${startTrainingDate || 'N/A'} To ${endTrainingDate || 'N/A'}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60, marginX + 135, marginY + 60);

    // Session details on the right side (continuing from doc info)
    doc.text(`Session: ${sessionName || 'N/A'}`, rightX, marginY + 39);
    doc.line(marginX + 135, marginY + 42, contentWidth + marginX, marginY + 42);
    
    doc.text(`Date: ${sessionDate || 'N/A'}`, rightX, marginY + 48);
    doc.line(marginX + 135, marginY + 51, contentWidth + marginX, marginY + 51);
    
    doc.text(`Time: ${sessionTime || 'N/A'}`, rightX, marginY + 57);
    doc.line(marginX + 135, marginY + 60, contentWidth + marginX, marginY + 60);

    // **Summary Row**
    const totalEmployees = safeAttendanceData.length;
    const presentCount = safeAttendanceData.filter(e => e.attendanceStatus === 1).length;
    const absentCount = totalEmployees - presentCount;
    
    doc.text(`Total: ${totalEmployees}`, marginX + 2, marginY + 66);
    doc.text(`Present: ${presentCount}`, marginX + 40, marginY + 66);
    doc.text(`Absent: ${absentCount}`, marginX + 80, marginY + 66);
    doc.text(`Generated: ${dayjs().format('DD-MM-YYYY HH:mm')}`, rightX, marginY + 66);
    doc.line(marginX, marginY + 70, contentWidth + marginX, marginY + 70);

    // **Legend for P/A**
    const legendY = marginY + 78;
    doc.setFontSize(9).setFont("helvetica", "bold");
    doc.text("Legend:", marginX + 2, legendY);
    
    // P - Present
    doc.setFillColor(144, 238, 144); // Light green
    doc.rect(marginX + 22, legendY - 3, 10, 5, 'F');
    doc.setDrawColor(0, 100, 0);
    doc.rect(marginX + 22, legendY - 3, 10, 5);
    doc.setFontSize(8).setFont("helvetica", "bold");
    doc.setTextColor(0, 100, 0);
    doc.text("P", marginX + 25, legendY);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text("= Present", marginX + 34, legendY);
    
    // A - Absent
    doc.setFillColor(255, 200, 200); // Light red
    doc.rect(marginX + 60, legendY - 3, 10, 5, 'F');
    doc.setDrawColor(200, 0, 0);
    doc.rect(marginX + 60, legendY - 3, 10, 5);
    doc.setFontSize(8).setFont("helvetica", "bold");
    doc.setTextColor(200, 0, 0);
    doc.text("A", marginX + 63, legendY);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text("= Absent", marginX + 72, legendY);

    doc.line(marginX, marginY + 80, contentWidth + marginX, marginY + 80);

    // **Build Table Data**
    if (safeAttendanceData.length > 0) {
      // Build headers
      const headers = ["Sr No.", "Employee Name", "Attendance Status"];

      // Build body rows
      const bodyData = safeAttendanceData.map((employee, index) => {
        return [
          (index + 1).toString(),
          employee.employeeName || 'N/A',
          employee.attendanceStatus === 1 ? 'P' : 'A',
        ];
      });

      // Custom cell styling for P (Green) and A (Red)
      const didDrawCell = (data) => {
        const cell = data.cell;
        const text = cell.text[0];
        
        if (data.section === 'body' && data.column.index === 2 && (text === 'P' || text === 'A')) {
          if (text === 'P') {
            data.doc.setFillColor(144, 238, 144); // Light green
            data.doc.rect(cell.x, cell.y, cell.width, cell.height, 'F');
            data.doc.setTextColor(0, 100, 0); // Dark green text
            data.doc.setFont("helvetica", "bold");
            data.doc.text('P', cell.x + cell.width / 2, cell.y + cell.height / 2 + 1, { align: 'center' });
          } else {
            data.doc.setFillColor(255, 200, 200); // Light red
            data.doc.rect(cell.x, cell.y, cell.width, cell.height, 'F');
            data.doc.setTextColor(200, 0, 0); // Dark red text
            data.doc.setFont("helvetica", "bold");
            data.doc.text('A', cell.x + cell.width / 2, cell.y + cell.height / 2 + 1, { align: 'center' });
          }
          // Draw cell border
          data.doc.setDrawColor(0, 0, 0);
          data.doc.rect(cell.x, cell.y, cell.width, cell.height);
          data.doc.setTextColor(0, 0, 0);
        }
      };

      const columnStyles = {
        0: { halign: 'center', cellWidth: 20 },   // Sr No
        1: { halign: 'left', cellWidth: 120 },    // Employee Name
        2: { halign: 'center', cellWidth: 50 },   // Attendance Status
      };

      doc.autoTable({
        startY: 95,
        head: [headers],
        body: bodyData,
        styles: {
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 10,
          textColor: [0, 0, 0],
          cellPadding: 3,
          minCellHeight: 10,
          valign: 'middle',
        },
        headStyles: {
          fillColor: [70, 130, 180],  // Steel blue
          textColor: [255, 255, 255],
          fontStyle: "bold",
          fontSize: 10,
          halign: 'center',
          valign: 'middle',
          minCellHeight: 12,
        },
        alternateRowStyles: { fillColor: [248, 248, 248] },
        columnStyles: columnStyles,
        theme: "grid",
        margin: { top: 95, left: marginX, right: marginX, bottom: 40 },
        tableLineWidth: 0.1,
        didDrawCell: didDrawCell,
        willDrawPage: (data) => {
          // Add header on new pages
          if (data.pageNumber > 1) {
            doc.setFontSize(12).setFont("helvetica", "bold");
            doc.text(`Session Attendance Report - ${sessionName} (Page ${data.pageNumber})`, pageWidth / 2, 15, { align: "center" });
            doc.setFontSize(10).setFont("helvetica", "normal");
            doc.text(`Training: ${trainingTitle}`, pageWidth / 2, 22, { align: "center" });
          }
        },
        showHead: 'everyPage',
        rowPageBreak: 'avoid',
      });

      // **Signatures Section**
      const finalY = doc.autoTable.previous.finalY;
      let signStartY = finalY + 20;

      // Check if signatures fit on current page
      if (signStartY + 50 > pageHeight - marginY) {
        doc.addPage();
        signStartY = 30;
      }

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Sign of Trainer: ____________________", marginX + 5, signStartY);
      signStartY += 20;
      doc.text("Sign of HR: ____________________", marginX + 5, signStartY);
      signStartY += 20;
      doc.text("Sign of HOD: ____________________", marginX + 5, signStartY);

    } else {
      doc.setFontSize(12).setFont("helvetica", "normal");
      doc.text("No attendance records found.", pageWidth / 2, 120, { align: "center" });
    }

    return doc;
  };

  const generatePDF = () => {
    try {
      const doc = createDoc();
      const pdfData = doc.output('datauristring');
      setPdfDataUrl(pdfData);
      setLoading(false);
      setPreviewOpen(true);
    } catch (error) {
      console.error("Error generating PDF:", error);
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = createDoc();
      doc.save(`Session_Attendance_${sessionName || 'Report'}_${dayjs().format('DD_MM_YYYY')}.pdf`);
    } catch (error) {
      console.error("Error downloading PDF:", error);
    }
  };

  const handleClosePreview = () => {
    setPreviewOpen(false);
    onClose?.();
  };

  if (loading) {
    return (
      <Modal open={true}>
        <Box sx={{ 
          width: "100%", 
          height: "100%", 
          display: 'flex', 
          alignItems: 'center', 
          justifyContent: 'center', 
          backgroundColor: "rgba(0,0,0,0.7)" 
        }}>
          <Typography sx={{ color: 'white', fontSize: 20 }}>Generating Report...</Typography>
        </Box>
      </Modal>
    );
  }

  return (
    <div>
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
      >
        <Box sx={{ 
          width: "95%", 
          maxWidth: "1100px",
          margin: "auto", 
          mt: 1, 
          backgroundColor: "white", 
          padding: 2, 
          borderRadius: 2, 
          height: '98vh', 
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column'
        }}>
          <Typography variant="h6" sx={{ mb: 1, fontWeight: 'bold', flexShrink: 0 }}>
            Session Attendance Report - PDF Preview (A4)
          </Typography>

          {pdfDataUrl ? (
            <>
              {/* Scrollable container for preview */}
              <Box sx={{ 
                flex: 1,
                overflow: 'auto', 
                border: '1px solid #ddd', 
                borderRadius: '4px',
                mb: 2,
                minHeight: '600px',
                maxHeight: 'calc(98vh - 120px)',
              }}>
                <iframe
                  src={pdfDataUrl}
                  width="100%"
                  height="100%"
                  style={{ 
                    border: 'none',
                    minHeight: '850px',
                  }}
                  title="PDF Preview"
                />
              </Box>
              
              <Box sx={{ display: 'flex', gap: 2, justifyContent: 'flex-end', flexShrink: 0 }}>
                <Typography variant="body2" sx={{ alignSelf: 'center', color: 'gray', mr: 'auto' }}>
                  💡 Scroll to view the full document
                </Typography>
                <Button variant="contained" color="primary" onClick={handleDownloadPDF}>
                  Download PDF
                </Button>
                <Button variant="outlined" color="secondary" onClick={handleClosePreview}>
                  Close
                </Button>
              </Box>
            </>
          ) : (
            <Typography>Failed to generate PDF</Typography>
          )}
        </Box>
      </Modal>
    </div>
  );
};

export default SessionAttendanceReport;
