import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png"; // Ensure PNG format is used
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import dayjs from 'dayjs';

const SkillMatrixReport = ({ employeeId, employeeName, selectedSkills, employeeSkillData, docNo = 'SKL-MATRIX-001', OriginDate, revNo = '1.0', revDate, onClose }) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null);
  const [previewOpen, setPreviewOpen] = useState(true);
  const [loading, setLoading] = useState(true);

  // Guard against invalid props
  const safeSelectedSkills = Array.isArray(selectedSkills) ? selectedSkills : [];

  useEffect(() => {
    console.log("Employee Skill Data:", employeeSkillData);
    console.log("Selected Skills:", selectedSkills);
    generatePDF();
  }, [employeeId, employeeName, selectedSkills, employeeSkillData]);

  // Helper function to get grade level info
  const getGradeLevel = (grade) => {
    const numGrade = parseInt(grade) || 0;
    const gradeLabels = {
      0: 'No Grade',
      1: 'Grade 1',
      2: 'Grade 2',
      3: 'Grade 3',
      4: 'Grade 4'
    };
    return { grade: numGrade, label: gradeLabels[numGrade] || gradeLabels[0] };
  };

  const generatePDF = () => {
    const createDoc = ({ forDownload = false } = {}) => {
      const doc = new jsPDF({ format: "a4" });
      doc.setProperties({
        title: "Skill Matrix Report",
        subject: "Employee Skill Matrix Detailed Report",
        author: "Aakar Foundry Pvt. Ltd.",
        keywords: "Skills, Matrix, Report, Competency",
        creator: "Generated by SkillMatrixReport",
      });

      let marginX = 10;
      let marginY = 10;
      let contentWidth = 190;

      // **Draw Outer Page Border**
      doc.rect(marginX, marginY, contentWidth, 277);

      // **Section 1: Logo & Company Name**
      try {
        doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
      } catch (e) {
        console.warn("Logo image failed to load:", e);
      }
      doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
      doc.setFontSize(13).setFont("helvetica", "bold");
      doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
      doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
      doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

      // **Section 2: Report Title (Centered)**
      let titleY = marginY + 3;
      doc.setFontSize(16).setFont("helvetica", "bold");
      doc.text("Skill Matrix Report", 105, titleY + 12, { align: "center" });

      // **Section 3: Right-Side Document Info**
      let rightX = marginX + 138;
      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
      doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
      doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
      doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
      doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
      doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
      doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
      doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);

      // **Vertical Line separating Document Info**
      doc.line(marginX + 135, marginY, marginX + 135, marginY + 68);

      // **Section 4: Employee Details**
      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text(`Employee ID: ${employeeId || 'N/A'}`, marginX + 2, marginY + 39);
      doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
      doc.text(`Employee Name: ${employeeName || 'N/A'}`, marginX + 2, marginY + 48);
      doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);
      doc.text(`Qualifications: ${employeeSkillData?.employeeQualification || 'N/A'}`, marginX + 2, marginY + 57);
      doc.line(marginX, marginY + 60, marginX + 135, marginY + 60);
      doc.text(`Experience (Years): ${employeeSkillData?.experienceInYears || 'N/A'}`, marginX + 2, marginY + 66);
      doc.line(marginX, marginY + 69, marginX + 135, marginY + 69);
      doc.text(`Selected Skills: ${safeSelectedSkills.length || 0}`, marginX + 2, marginY + 75);
      doc.line(marginX, marginY + 78, marginX + 135, marginY + 78);
      doc.text(`Generated Date: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 2, marginY + 84);
      doc.line(marginX, marginY + 87, contentWidth + 10, marginY + 87);

      // **Table Data: Skill Matrix with all selected skills**
      if (safeSelectedSkills.length > 0) {
        // Helper function to draw 2x2 grade matrix squares
        const drawGradeMatrix = (gradeValue, x, y, cellWidth, cellHeight) => {
          // Don't render empty matrix if no grade
          if (gradeValue <= 0) return;

          const squareSize = 4.5; // Unified square size
          const spacing = 1.2; // Unified spacing
          const totalSize = squareSize * 2 + spacing;

          // Center the matrix in the cell
          const startX = x + (cellWidth - totalSize) / 2;
          const startY = y + (cellHeight - totalSize) / 2;

          // Draw 2x2 matrix
          for (let row = 0; row < 2; row++) {
            for (let col = 0; col < 2; col++) {
              const squareX = startX + col * (squareSize + spacing);
              const squareY = startY + row * (squareSize + spacing);
              const squareIndex = row * 2 + col + 1;

              const isFilled = squareIndex <= gradeValue;

              // Draw fill first, then border
              if (isFilled) {
                doc.setFillColor(59, 130, 246); // Blue fill
                doc.rect(squareX, squareY, squareSize, squareSize, 'F');
              }

              // Draw border on top
              doc.setDrawColor(0, 0, 0);
              doc.setLineWidth(0.3);
              doc.rect(squareX, squareY, squareSize, squareSize);
            }
          }
        };

        const tableData = [];

        safeSelectedSkills.forEach((skill, index) => {
          // Find the grade for this skill in the employee data
          let grade = 0;
          let skillId = skill.id;

          if (employeeSkillData && employeeSkillData.skills) {
            grade = employeeSkillData.skills[skillId] || 0;
          }

          const gradeInfo = getGradeLevel(grade);

          tableData.push([
            (index + 1).toString(),
            { content: skill.label, styles: { fontSize: 10, fontStyle: 'normal' } },
            { content: '', styles: { fontSize: 9, halign: 'center', valign: 'middle' }, gradeValue: gradeInfo.grade },
          ]);
        });

        console.log("Total Skills Expected:", safeSelectedSkills.length);
        console.log("Total Skills in Table:", tableData.length);
        console.log("Skills Match Expected:", tableData.length === safeSelectedSkills.length ? "✓ YES" : "✗ NO");

        doc.autoTable({
          startY: 95,
          head: [["Sr No.", "Skill Name", "Grade Matrix"]],
          body: tableData,
          styles: {
            lineWidth: 0.1,
            lineColor: [0, 0, 0],
            fontSize: 9,
            textColor: [0, 0, 0],
            cellPadding: 3,
            minCellHeight: 12,
          },
          headStyles: {
            fillColor: [200, 200, 200],
            textColor: [0, 0, 0],
            fontStyle: "bold",
            fontSize: 10,
          },
          alternateRowStyles: { fillColor: false },
          columnStyles: {
            0: { halign: 'center', cellWidth: 15 },
            1: { halign: 'left', cellWidth: 135 },
            2: { halign: 'center', cellWidth: 40 },
          },
          theme: "grid",
          margin: { top: 20, left: 10, right: 10, bottom: 20 },
          tableLineWidth: 0.1,
          didDrawCell: (data) => {
            if (data.column.index === 2 && data.row.index !== -1) {
              const gradeValue = data.row?.raw?.[2]?.gradeValue ?? 0;
              drawGradeMatrix(gradeValue, data.cell.x, data.cell.y, data.cell.width, data.cell.height);
            }
          },
        });

        // **Signatures**
        let signStartY = doc.autoTable.previous.finalY + 10;

        doc.setFontSize(11).setFont("helvetica", "bold");
        doc.text("Employee Sign:                  ", marginX + 2, signStartY);
        signStartY += 15;
        doc.text("Manager Sign:                   ", marginX + 2, signStartY);
        signStartY += 15;
        doc.text("HR Sign:                        ", marginX + 2, signStartY);
      } else {
        doc.text("No skill data found", 10, 90);
      }

      return doc;
    };

    try {
      const doc = createDoc({ forDownload: false });
      const pdfData = doc.output('datauristring');
      setPdfDataUrl(pdfData);
      setLoading(false);
      setPreviewOpen(true);
    } catch (error) {
      console.error("Error generating PDF:", error);
      setLoading(false);
    }
  };

  const handleClosePreview = () => {
    console.log('Closing skill matrix report modal');
    setPreviewOpen(false);
    setPdfDataUrl(null);
    if (onClose) {
      onClose();
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF({ format: "a4" });
      doc.setProperties({
        title: "Skill Matrix Report",
        subject: "Employee Skill Matrix Detailed Report",
        author: "Aakar Foundry Pvt. Ltd.",
        keywords: "Skills, Matrix, Report, Competency",
        creator: "Generated by SkillMatrixReport",
      });

      let marginX = 10;
      let marginY = 10;
      let contentWidth = 190;

      // **Draw Outer Page Border**
      doc.rect(marginX, marginY, contentWidth, 277);

      // **Section 1: Logo & Company Name**
      try {
        doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
      } catch (e) {
        console.warn("Logo image failed to load:", e);
      }
      doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
      doc.setFontSize(13).setFont("helvetica", "bold");
      doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
      doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
      doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

      // **Section 2: Report Title (Centered)**
      let titleY = marginY + 3;
      doc.setFontSize(16).setFont("helvetica", "bold");
      doc.text("Skill Matrix Report", 105, titleY + 12, { align: "center" });

      // **Section 3: Right-Side Document Info**
      let rightX = marginX + 138;
      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
      doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
      doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
      doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
      doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
      doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
      doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
      doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);

      // **Vertical Line separating Document Info**
      doc.line(marginX + 135, marginY, marginX + 135, marginY + 68);

      // **Section 4: Employee Details**
      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text(`Employee ID: ${employeeId || 'N/A'}`, marginX + 2, marginY + 39);
      doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
      doc.text(`Employee Name: ${employeeName || 'N/A'}`, marginX + 2, marginY + 48);
      doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);
      doc.text(`Qualifications: ${employeeSkillData?.employeeQualification || 'N/A'}`, marginX + 2, marginY + 57);
      doc.line(marginX, marginY + 60, marginX + 135, marginY + 60);
      doc.text(`Experience (Years): ${employeeSkillData?.experienceInYears || 'N/A'}`, marginX + 2, marginY + 66);
      doc.line(marginX, marginY + 69, marginX + 135, marginY + 69);
      doc.text(`Selected Skills: ${safeSelectedSkills.length || 0}`, marginX + 2, marginY + 75);
      doc.line(marginX, marginY + 78, marginX + 135, marginY + 78);
      doc.text(`Generated Date: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 2, marginY + 84);
      doc.line(marginX, marginY + 87, contentWidth + 10, marginY + 87);

      // **Table Data: Skill Matrix with all selected skills**
      if (safeSelectedSkills.length > 0) {
        // Helper function to draw 2x2 grade matrix squares
        const drawGradeMatrix = (gradeValue, x, y, cellWidth, cellHeight) => {
          // Don't render empty matrix if no grade
          if (gradeValue <= 0) return;

          const squareSize = 4.5; // Unified square size
          const spacing = 1.2; // Unified spacing
          const totalSize = squareSize * 2 + spacing;

          // Center the matrix in the cell
          const startX = x + (cellWidth - totalSize) / 2;
          const startY = y + (cellHeight - totalSize) / 2;

          // Draw 2x2 matrix
          for (let row = 0; row < 2; row++) {
            for (let col = 0; col < 2; col++) {
              const squareX = startX + col * (squareSize + spacing);
              const squareY = startY + row * (squareSize + spacing);
              const squareIndex = row * 2 + col + 1;

              const isFilled = squareIndex <= gradeValue;

              // Draw fill first, then border
              if (isFilled) {
                doc.setFillColor(59, 130, 246); // Blue fill
                doc.rect(squareX, squareY, squareSize, squareSize, 'F');
              }

              // Draw border on top
              doc.setDrawColor(0, 0, 0);
              doc.setLineWidth(0.3);
              doc.rect(squareX, squareY, squareSize, squareSize);
            }
          }
        };

        const tableData = [];

        safeSelectedSkills.forEach((skill, index) => {
          // Find the grade for this skill in the employee data
          let grade = 0;
          let skillId = skill.id;

          if (employeeSkillData && employeeSkillData.skills) {
            grade = employeeSkillData.skills[skillId] || 0;
          }

          const gradeInfo = getGradeLevel(grade);

          tableData.push([
            (index + 1).toString(),
            { content: skill.label, styles: { fontSize: 10, fontStyle: 'normal' } },
            { content: '', styles: { fontSize: 9, halign: 'center', valign: 'middle' }, gradeValue: gradeInfo.grade },
          ]);
        });

        doc.autoTable({
          startY: 95,
          head: [["Sr No.", "Skill Name", "Grade Matrix"]],
          body: tableData,
          styles: {
            lineWidth: 0.1,
            lineColor: [0, 0, 0],
            fontSize: 9,
            textColor: [0, 0, 0],
            cellPadding: 3,
            minCellHeight: 12,
          },
          headStyles: {
            fillColor: [200, 200, 200],
            textColor: [0, 0, 0],
            fontStyle: "bold",
            fontSize: 10,
          },
          alternateRowStyles: { fillColor: false },
          columnStyles: {
            0: { halign: 'center', cellWidth: 15 },
            1: { halign: 'left', cellWidth: 135 },
            2: { halign: 'center', cellWidth: 40 },
          },
          theme: "grid",
          margin: { top: 20, left: 10, right: 10, bottom: 20 },
          tableLineWidth: 0.1,
          didDrawCell: (data) => {
            if (data.column.index === 2 && data.row.index !== -1) {
              const gradeValue = data.row?.raw?.[2]?.gradeValue ?? 0;
              drawGradeMatrix(gradeValue, data.cell.x, data.cell.y, data.cell.width, data.cell.height);
            }
          },
        });

        // **Signatures**
        let signStartY = doc.autoTable.previous.finalY + 10;

        doc.setFontSize(11).setFont("helvetica", "bold");
        doc.text("Employee Sign:                  ", marginX + 2, signStartY);
        signStartY += 15;
        doc.text("Manager Sign:                   ", marginX + 2, signStartY);
        signStartY += 15;
        doc.text("HR Sign:                        ", marginX + 2, signStartY);
      } else {
        doc.text("No skill data found", 10, 90);
      }

      // Download the PDF
      doc.save(`SkillMatrixReport_${employeeId}_${dayjs().format("DD_MM_YYYY")}.pdf`);
    } catch (error) {
      console.error("Error downloading PDF:", error);
    }
  };

  return (
    <div>
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
      >
        <Box sx={{ width: "85%", margin: "auto", mt: 5, backgroundColor: "white", padding: 2, borderRadius: 2, maxHeight: '90vh', overflow: 'auto' }}>
          <Typography variant="h6" sx={{ mb: 2, fontWeight: 'bold' }}>
            Skill Matrix Report - PDF Preview
          </Typography>

          {pdfDataUrl ? (
            <iframe
              src={pdfDataUrl}
              width="100%"
              height="600px"
              style={{ border: '1px solid #ddd', borderRadius: '4px' }}
              title="PDF Preview"
            />
          ) : (
            <Typography variant="body1">Loading PDF preview...</Typography>
          )}

          <div style={{ marginTop: '20px', display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <Button 
              onClick={handleDownloadPDF} 
              variant="contained" 
              color="primary"
            >
              Download PDF
            </Button>
            <Button 
              onClick={handleClosePreview} 
              variant="outlined" 
              color="secondary"
            >
              Close Preview
            </Button>
          </div>
        </Box>
      </Modal>
    </div>
  );
};

export default SkillMatrixReport;
