import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png";
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import dayjs from 'dayjs';

const SkillMatrixDeptReport = ({ 
  departmentName, 
  departmentId,
  employeeData, 
  selectedSkills, 
  onClose,
  docNo = 'SKILL-MATRIX-001',
  OriginDate,
  revNo = '1.0',
  revDate
}) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null);
  const [previewOpen, setPreviewOpen] = useState(true);
  const [loading, setLoading] = useState(true);

  // Guard against invalid props
  const safeEmployeeData = Array.isArray(employeeData) ? employeeData : [];
  const safeSelectedSkills = Array.isArray(selectedSkills) ? selectedSkills : [];

  useEffect(() => {
    console.log("Employee Data:", employeeData);
    console.log("Selected Skills:", selectedSkills);
    generatePDF();
  }, [employeeData, selectedSkills]);

  // Helper function to draw 2x2 grade matrix squares (all blue like DepartmentSkillMatrixReport)
  const drawGradeMatrix = (gradeValue, x, y, cellWidth, cellHeight, docInstance) => {
    // Don't render empty matrix if no grade
    if (gradeValue <= 0) return;

    const squareSize = 4.5; // Unified square size
    const spacing = 1.2; // Unified spacing
    const totalSize = squareSize * 2 + spacing;

    // Center the matrix in the cell
    const startX = x + (cellWidth - totalSize) / 2;
    const startY = y + (cellHeight - totalSize) / 2;

    // Draw 2x2 matrix
    for (let row = 0; row < 2; row++) {
      for (let col = 0; col < 2; col++) {
        const squareX = startX + col * (squareSize + spacing);
        const squareY = startY + row * (squareSize + spacing);
        const squareIndex = row * 2 + col + 1;

        const isFilled = squareIndex <= gradeValue;

        // Draw fill first, then border
        if (isFilled) {
          docInstance.setFillColor(59, 130, 246); // Blue fill (same as DepartmentSkillMatrixReport)
          docInstance.rect(squareX, squareY, squareSize, squareSize, 'F');
        }

        // Draw border on top
        docInstance.setDrawColor(0, 0, 0);
        docInstance.setLineWidth(0.3);
        docInstance.rect(squareX, squareY, squareSize, squareSize);
      }
    }
  };

  const createDoc = () => {
    // A3 format: 297mm x 420mm (landscape for better skill columns fit)
    const doc = new jsPDF({ 
      format: "a3",
      orientation: "landscape"
    });
    
    doc.setProperties({
      title: "Skill Matrix Report",
      subject: "Department Skill Matrix Grid Report",
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Skills, Matrix, Report, Department, Grid",
      creator: "Generated by SkillMatrixDeptReport",
    });

    const pageWidth = doc.internal.pageSize.getWidth();  // 420mm for A3 landscape
    const pageHeight = doc.internal.pageSize.getHeight(); // 297mm for A3 landscape
    const marginX = 10;
    const marginY = 10;
    const contentWidth = pageWidth - (marginX * 2);
    const contentHeight = pageHeight - (marginY * 2);

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, contentHeight);

    // **Section 1: Logo & Company Name**
    try {
      doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    } catch (e) {
      console.warn("Logo image failed to load:", e);
    }
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    // **Section 2: Report Title (Centered)**
    doc.setFontSize(18).setFont("helvetica", "bold");
    doc.text("Skill Matrix Report", pageWidth / 2, marginY + 15, { align: "center" });

    // **Section 3: Right-Side Document Info**
    let rightX = pageWidth - marginX - 60;
    doc.setFontSize(10).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(rightX - 3, marginY + 8, pageWidth - marginX, marginY + 8);
    doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
    doc.line(rightX - 3, marginY + 16, pageWidth - marginX, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(rightX - 3, marginY + 24, pageWidth - marginX, marginY + 24);
    doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
    doc.line(rightX - 3, marginY + 33, pageWidth - marginX, marginY + 33);

    // Vertical line for right section
    doc.line(rightX - 3, marginY, rightX - 3, marginY + 55);

    // **Section 4: Department Details**
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Department: ${departmentName || 'N/A'}`, marginX + 2, marginY + 39);
    doc.line(marginX, marginY + 42, rightX - 3, marginY + 42);
    doc.text(`Total Employees: ${safeEmployeeData.length || 0}`, marginX + 2, marginY + 48);
    doc.text(`Total Skills: ${safeSelectedSkills.length || 0}`, marginX + 100, marginY + 48);
    doc.line(marginX, marginY + 51, rightX - 3, marginY + 51);
    doc.text(`Generated Date: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60, pageWidth - marginX, marginY + 60);

    // **Grade Legend (Simple - all blue)**
    const legendStartX = marginX + 250;
    const legendY = marginY + 48;
    doc.setFontSize(9).setFont("helvetica", "bold");
    doc.text("Grade Matrix:", legendStartX, legendY);
    
    // Draw example 2x2 matrix
    const exampleX = legendStartX + 28;
    const exampleY = legendY - 3;
    const sqSize = 3.5;
    const sqSpacing = 0.8;
    for (let i = 0; i < 4; i++) {
      const row = Math.floor(i / 2);
      const col = i % 2;
      doc.setFillColor(59, 130, 246); // Blue
      doc.rect(exampleX + col * (sqSize + sqSpacing), exampleY + row * (sqSize + sqSpacing), sqSize, sqSize, 'F');
      doc.setDrawColor(0, 0, 0);
      doc.rect(exampleX + col * (sqSize + sqSpacing), exampleY + row * (sqSize + sqSpacing), sqSize, sqSize);
    }
    doc.setFontSize(8).setFont("helvetica", "normal");
    doc.text("= Filled squares indicate grade level (1-4)", exampleX + 12, legendY);

    // **Build Table Data**
    if (safeEmployeeData.length > 0 && safeSelectedSkills.length > 0) {
      // Calculate how many skills can fit per page
      const fixedColumnsWidth = 15 + 50 + 45; // Sr No + Name + Qualification
      const availableWidthForSkills = contentWidth - fixedColumnsWidth - 10;
      const minSkillColumnWidth = 22; // Minimum width to show grade matrix properly
      const maxSkillsPerPage = Math.floor(availableWidthForSkills / minSkillColumnWidth);
      
      // Split skills into chunks if too many
      const skillChunks = [];
      for (let i = 0; i < safeSelectedSkills.length; i += maxSkillsPerPage) {
        skillChunks.push(safeSelectedSkills.slice(i, i + maxSkillsPerPage));
      }

      let currentPage = 1;
      const totalPages = skillChunks.length;

      // Generate table for each skill chunk
      skillChunks.forEach((skillChunk, chunkIndex) => {
        if (chunkIndex > 0) {
          doc.addPage();
          currentPage++;
          
          // Draw header for continuation pages
          doc.setFontSize(12).setFont("helvetica", "bold");
          doc.text(`Skill Matrix Report - ${departmentName} (Page ${currentPage}/${totalPages})`, pageWidth / 2, 15, { align: "center" });
          
          // Draw skill range info
          const startSkillNum = chunkIndex * maxSkillsPerPage + 1;
          const endSkillNum = Math.min((chunkIndex + 1) * maxSkillsPerPage, safeSelectedSkills.length);
          doc.setFontSize(10).setFont("helvetica", "normal");
          doc.text(`Skills ${startSkillNum} - ${endSkillNum} of ${safeSelectedSkills.length}`, pageWidth / 2, 22, { align: "center" });
        }

        // Build headers for this chunk
        const headers = ["Sr No.", "Employee Name", "Qualification"];
        skillChunk.forEach(skill => {
          // Truncate long skill names
          const maxLen = 15;
          const skillName = skill.label.length > maxLen 
            ? skill.label.substring(0, maxLen - 2) + '..' 
            : skill.label;
          headers.push(skillName);
        });

        // Build body rows for this chunk
        const bodyData = safeEmployeeData.map((employee, index) => {
          const row = [
            (index + 1).toString(),
            employee.employeeName || 'N/A',
            employee.employeeQualification || 'N/A',
          ];

          // Add grade for each skill in this chunk
          skillChunk.forEach(skill => {
            const grade = employee.skills?.[skill.id] || 0;
            row.push({ content: '', gradeValue: grade });
          });

          return row;
        });

        // Calculate column widths for this chunk
        const skillsInChunk = skillChunk.length;
        const skillColumnWidth = Math.max(minSkillColumnWidth, availableWidthForSkills / skillsInChunk);

        const columnStyles = {
          0: { halign: 'center', cellWidth: 15 },  // Sr No
          1: { halign: 'left', cellWidth: 50 },    // Employee Name
          2: { halign: 'left', cellWidth: 45 },    // Qualification
        };

        // Add column styles for each skill in chunk
        skillChunk.forEach((_, idx) => {
          columnStyles[idx + 3] = { halign: 'center', cellWidth: skillColumnWidth };
        });

        const tableStartY = chunkIndex === 0 ? 70 : 30;

        doc.autoTable({
          startY: tableStartY,
          head: [headers],
          body: bodyData,
          styles: {
            lineWidth: 0.1,
            lineColor: [0, 0, 0],
            fontSize: 8,
            textColor: [0, 0, 0],
            cellPadding: 2,
            minCellHeight: 14,
            valign: 'middle',
          },
          headStyles: {
            fillColor: [70, 130, 180],  // Steel blue
            textColor: [255, 255, 255],
            fontStyle: "bold",
            fontSize: 7,
            halign: 'center',
            valign: 'middle',
            minCellHeight: 18,
            cellPadding: 1,
          },
          alternateRowStyles: { fillColor: [248, 248, 248] },
          columnStyles: columnStyles,
          theme: "grid",
          margin: { top: tableStartY, left: marginX, right: marginX, bottom: 30 },
          tableLineWidth: 0.1,
          didDrawCell: (data) => {
            // Draw grade matrix for skill columns (index >= 3)
            if (data.column.index >= 3 && data.section === 'body') {
              const gradeValue = data.row?.raw?.[data.column.index]?.gradeValue ?? 0;
              drawGradeMatrix(gradeValue, data.cell.x, data.cell.y, data.cell.width, data.cell.height, doc);
            }
          },
          willDrawPage: (data) => {
            // Add header on new pages (for row overflow)
            if (data.pageNumber > 1 && chunkIndex === 0) {
              doc.setFontSize(12).setFont("helvetica", "bold");
              doc.text(`Skill Matrix Report - ${departmentName} (Continued)`, pageWidth / 2, 15, { align: "center" });
            }
          },
          showHead: 'everyPage',
          rowPageBreak: 'avoid',
        });
      });

      // **Signatures Section** (only on last page)
      const finalY = doc.autoTable.previous.finalY;
      let signStartY = finalY + 15;

      // Check if signatures fit on current page
      if (signStartY + 40 > pageHeight - marginY) {
        doc.addPage();
        signStartY = 30;
      }

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Prepared By: ____________________", marginX + 10, signStartY);
      doc.text("Reviewed By: ____________________", marginX + 150, signStartY);
      doc.text("Approved By: ____________________", marginX + 290, signStartY);
      
      signStartY += 20;
      doc.text("Manager Sign: ____________________", marginX + 10, signStartY);
      doc.text("HR Sign: ____________________", marginX + 150, signStartY);
      doc.text("HOD Sign: ____________________", marginX + 290, signStartY);

    } else {
      doc.setFontSize(12).setFont("helvetica", "normal");
      doc.text("No data available for the report.", pageWidth / 2, 100, { align: "center" });
    }

    return doc;
  };

  const generatePDF = () => {
    try {
      const doc = createDoc();
      const pdfData = doc.output('datauristring');
      setPdfDataUrl(pdfData);
      setLoading(false);
      setPreviewOpen(true);
    } catch (error) {
      console.error("Error generating PDF:", error);
      setLoading(false);
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = createDoc();
      doc.save(`SkillMatrix_${departmentName}_${dayjs().format("DD_MM_YYYY")}.pdf`);
    } catch (error) {
      console.error("Error downloading PDF:", error);
    }
  };

  const handleClosePreview = () => {
    setPreviewOpen(false);
    onClose?.();
  };

  if (loading) {
    return (
      <Modal open={true}>
        <Box sx={{ 
          width: "100%", 
          height: "100%", 
          display: 'flex', 
          alignItems: 'center', 
          justifyContent: 'center', 
          backgroundColor: "rgba(0,0,0,0.7)" 
        }}>
          <Typography sx={{ color: 'white', fontSize: 20 }}>Generating Report...</Typography>
        </Box>
      </Modal>
    );
  }

  return (
    <div>
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
      >
        <Box sx={{ 
          width: "98%", 
          maxWidth: "1800px",
          margin: "auto", 
          mt: 1, 
          backgroundColor: "white", 
          padding: 2, 
          borderRadius: 2, 
          height: '98vh', 
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column'
        }}>
          <Typography variant="h6" sx={{ mb: 1, fontWeight: 'bold', flexShrink: 0 }}>
            Skill Matrix Report - PDF Preview (A3 Landscape)
          </Typography>

          {pdfDataUrl ? (
            <>
              {/* Scrollable container for A3 preview with zoom */}
              <Box sx={{ 
                flex: 1,
                overflow: 'auto', 
                border: '1px solid #ddd', 
                borderRadius: '4px',
                mb: 2,
                minHeight: '600px',
                maxHeight: 'calc(98vh - 120px)',
                '& iframe': {
                  minWidth: '1400px',  // Allow horizontal scroll for A3
                  minHeight: '900px',
                }
              }}>
                <iframe
                  src={pdfDataUrl}
                  width="100%"
                  height="100%"
                  style={{ 
                    border: 'none',
                    minWidth: '1400px',
                    minHeight: '900px',
                  }}
                  title="PDF Preview"
                />
              </Box>
              
              <Box sx={{ display: 'flex', gap: 2, justifyContent: 'flex-end', flexShrink: 0 }}>
                <Typography variant="body2" sx={{ alignSelf: 'center', color: 'gray', mr: 'auto' }}>
                  💡 Tip: Scroll horizontally and vertically to view the full A3 document
                </Typography>
                <Button variant="contained" color="primary" onClick={handleDownloadPDF}>
                  Download PDF
                </Button>
                <Button variant="outlined" color="secondary" onClick={handleClosePreview}>
                  Close
                </Button>
              </Box>
            </>
          ) : (
            <Typography>Failed to generate PDF</Typography>
          )}
        </Box>
      </Modal>
    </div>
  );
};

export default SkillMatrixDeptReport;
