import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png"; // Ensure PNG format is used
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import { Document, Page, pdfjs } from 'react-pdf';
import dayjs from 'dayjs';

// Set workerSrc for React-PDF
pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

const TrainingReportGenerator = ({ employeeId, trainings, docNo = 'TRAIN-001', OriginDate, revNo = '1.0', revDate, onClose }) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null); // Store generated PDF data URL
  const [previewOpen, setPreviewOpen] = useState(true); // State to control modal visibility - starts TRUE
  const [loading, setLoading] = useState(true); // For loading state

  useEffect(() => {
    // Generate PDF preview on component mount
    console.log("Trainings Data:", trainings);
    generatePDF();
  }, []);

  const generatePDF = () => {
    const doc = new jsPDF({ format: "a4" });
    doc.setProperties({
      title: "Training Report",
      subject: "Employee Training Participations Report",
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Training, Participations, Report",
      creator: "Generated by TrainingReportGenerator",
    });

    let marginX = 10;
    let marginY = 10;
    let contentWidth = 190; // Full width with margins

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, 277); // A4 page height is 297mm

    // **Section 1: Logo & Company Name**
    doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    // **Section 2: Report Title (Centered)**
    let titleY = marginY + 3;
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text("Training Report", 105, titleY + 12, { align: "center" });

    // **Section 3: Right-Side Document Info**
    let rightX = marginX + 138;
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
    doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
    doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
    doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
    doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);

    // **Vertical Line separating Document Info**
    doc.line(marginX + 135, marginY, marginX + 135, marginY + 68);

    // **Section 4: Training Summary**
    const ongoingCount = trainings.filter(t => t.trainingStatus === 'Ongoing').length;
    const completedCount = trainings.filter(t => t.trainingStatus === 'Completed').length;
    const upcomingCount = trainings.filter(t => t.trainingStatus === 'Upcoming').length;

    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Employee ID: ${employeeId || 'N/A'}`, marginX + 2, marginY + 39);
    doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
    doc.text(`Total Trainings: ${trainings.length || 0}`, marginX + 2, marginY + 48);
    doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);
    doc.text(`Ongoing: ${ongoingCount} | Completed: ${completedCount} | Upcoming: ${upcomingCount}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60, marginX + 135, marginY + 60);
    doc.text(`Generated Date: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 2, marginY + 65);
    doc.line(marginX, marginY + 68, contentWidth + 10, marginY + 68);

    // **Table Data: Trainings**
    if (trainings && trainings.length > 0) {
      const tableData = trainings.map((training, index) => [
        (index + 1).toString(),
        training.trainingTitle || 'N/A',
        training.trainerName || 'N/A',
        training.skillNames || 'N/A',
        training.startTrainingDate || 'N/A',
        training.endTrainingDate || 'N/A',
        training.trainingStatus || 'N/A',
      ]);

      doc.autoTable({
        startY: 80,
        head: [["Sr No.", "Training Title", "Trainer Name", "Skills", "Start Date", "End Date", "Status"]],
        body: tableData,
        styles: {
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 9,
          textColor: [0, 0, 0],
        },
        headStyles: {
          fillColor: [255, 255, 255],
          textColor: [0, 0, 0],
          fontStyle: "bold",
        },
        alternateRowStyles: { fillColor: false },
        theme: "grid",
        margin: { top: 20, left: 10, right: 10, bottom: 20 },
        tableLineWidth: 0,
        columnStyles: {
          0: { halign: 'center', cellWidth: 15 },
          1: { halign: 'left', cellWidth: 35 },
          2: { halign: 'left', cellWidth: 25 },
          3: { halign: 'left', cellWidth: 25 },
          4: { halign: 'center', cellWidth: 20 },
          5: { halign: 'center', cellWidth: 20 },
          6: { halign: 'center', cellWidth: 20 },
        },
      });

      // **Signatures**
      let signStartY = doc.autoTable.previous.finalY + 10;

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Employee Sign:                  ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("Manager Sign:                   ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("HR Sign:                        ", marginX + 2, signStartY);
    } else {
      doc.text("No training data found", 10, 90);
    }

    // Generate the PDF data URL
    const pdfData = doc.output('datauristring');
    setPdfDataUrl(pdfData);
    setLoading(false);
    setPreviewOpen(true);
  };

  const handleClosePreview = () => {
    console.log('Closing training report modal');
    setPreviewOpen(false);
    setPdfDataUrl(null);
    if (onClose) {
      onClose(); // Call parent's onClose callback
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ format: "a4" });
    doc.setProperties({
      title: "Training Report",
    });

    let marginX = 10;
    let marginY = 10;
    let contentWidth = 190;

    doc.rect(marginX, marginY, contentWidth, 277);
    doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    let titleY = marginY + 3;
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text("Training Report", 105, titleY + 12, { align: "center" });

    let rightX = marginX + 138;
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
    doc.text(`Origin Date: ${OriginDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 13);
    doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
    doc.text(`Rev Date: ${revDate || dayjs().format('DD-MM-YYYY')}`, rightX, marginY + 30);
    doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);
    doc.line(marginX + 135, marginY, marginX + 135, marginY + 68);

    const ongoingCount = trainings.filter(t => t.trainingStatus === 'Ongoing').length;
    const completedCount = trainings.filter(t => t.trainingStatus === 'Completed').length;
    const upcomingCount = trainings.filter(t => t.trainingStatus === 'Upcoming').length;

    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Employee ID: ${employeeId || 'N/A'}`, marginX + 2, marginY + 39);
    doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
    doc.text(`Total Trainings: ${trainings.length || 0}`, marginX + 2, marginY + 48);
    doc.line(marginX, marginY + 51, marginX + 135, marginY + 51);
    doc.text(`Ongoing: ${ongoingCount} | Completed: ${completedCount} | Upcoming: ${upcomingCount}`, marginX + 2, marginY + 57);
    doc.line(marginX, marginY + 60, marginX + 135, marginY + 60);
    doc.text(`Generated Date: ${dayjs().format('DD-MM-YYYY HH:mm:ss')}`, marginX + 2, marginY + 65);
    doc.line(marginX, marginY + 68, contentWidth + 10, marginY + 68);

    if (trainings && trainings.length > 0) {
      const tableData = trainings.map((training, index) => [
        (index + 1).toString(),
        training.trainingTitle || 'N/A',
        training.trainerName || 'N/A',
        training.skillNames || 'N/A',
        training.startTrainingDate || 'N/A',
        training.endTrainingDate || 'N/A',
        training.trainingStatus || 'N/A',
      ]);

      doc.autoTable({
        startY: 80,
        head: [["Sr No.", "Training Title", "Trainer Name", "Skills", "Start Date", "End Date", "Status"]],
        body: tableData,
        styles: {
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 9,
          textColor: [0, 0, 0],
        },
        headStyles: {
          fillColor: [255, 255, 255],
          textColor: [0, 0, 0],
          fontStyle: "bold",
        },
        alternateRowStyles: { fillColor: false },
        theme: "grid",
        margin: { top: 20, left: 10, right: 10, bottom: 20 },
        tableLineWidth: 0,
        columnStyles: {
          0: { halign: 'center', cellWidth: 15 },
          1: { halign: 'left', cellWidth: 35 },
          2: { halign: 'left', cellWidth: 25 },
          3: { halign: 'left', cellWidth: 25 },
          4: { halign: 'center', cellWidth: 20 },
          5: { halign: 'center', cellWidth: 20 },
          6: { halign: 'center', cellWidth: 20 },
        },
      });

      let signStartY = doc.autoTable.previous.finalY + 10;
      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Employee Sign:                  ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("Manager Sign:                   ", marginX + 2, signStartY);
      signStartY += 15;
      doc.text("HR Sign:                        ", marginX + 2, signStartY);
    }

    doc.save(`Training_Report_${employeeId}_${dayjs().format('YYYY-MM-DD')}.pdf`);
  };

  return (
    <div>
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
      >
        <Box sx={{ width: "85%", margin: "auto", mt: 5, backgroundColor: "white", padding: 2, borderRadius: 2 }}>
          <Typography variant="h6" sx={{ mb: 1 }}>
            Training Report - PDF Preview
          </Typography>

          {pdfDataUrl ? (
            <iframe
              src={pdfDataUrl}
              width="100%"
              height="500px"
              style={{ border: 'none' }}
              title="PDF Preview"
            />
          ) : (
            <Typography variant="body1">Loading PDF preview...</Typography>
          )}

          <div style={{ marginTop: '20px', display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <Button 
              onClick={handleDownloadPDF} 
              variant="contained" 
              color="primary"
            >
              Download PDF
            </Button>
            <Button 
              onClick={handleClosePreview} 
              variant="outlined" 
              color="secondary"
            >
              Close Preview
            </Button>
          </div>
        </Box>
      </Modal>
    </div>
  );
};

export default TrainingReportGenerator;
