import jsPDF from "jspdf";
import "jspdf-autotable";
import logo from "../../assets/logo.png";
import React, { useState, useEffect } from 'react';
import { Modal, Box, Typography, Button } from "@mui/material";
import dayjs from 'dayjs';

const TrainerReportGenerator = ({ 
  trainerName, 
  trainingsData, 
  onClose 
}) => {
  const [pdfDataUrl, setPdfDataUrl] = useState(null);
  const [previewOpen, setPreviewOpen] = useState(true);
  const [loading, setLoading] = useState(true);

  // Report metadata
  const reportTitle = "Trainer Report";
  const docNo = "AFPL/HR/TR/01";
  const OriginDate = "01-01-2024";
  const revNo = "00";
  const revDate = dayjs().format("DD-MM-YYYY");
  const location = "Kolhapur";

  useEffect(() => {
    if (trainingsData && trainingsData.length > 0) {
      generatePDF();
    }
  }, [trainingsData]);

  const createDoc = () => {
    const doc = new jsPDF({ format: "a4" });
    doc.setProperties({
      title: reportTitle,
      subject: "Trainer Training Report",
      author: "Aakar Foundry Pvt. Ltd.",
      keywords: "Trainer, Training, Report",
      creator: "Generated by TrainerReportGenerator",
    });

    let marginX = 10;
    let marginY = 10;
    let contentWidth = 190;

    // **Draw Outer Page Border**
    doc.rect(marginX, marginY, contentWidth, 277);

    // **Section 1: Logo & Company Name**
    doc.addImage(logo, "PNG", marginX + 20, marginY + 3, 20, 20);
    doc.line(marginX, marginY + 25, marginX + 57, marginY + 25);
    doc.setFontSize(13).setFont("helvetica", "bold");
    doc.text("Aakar Foundry Pvt. Ltd.", marginX + 2, marginY + 30);
    doc.line(marginX, marginY + 33, marginX + 135, marginY + 33);
    doc.line(marginX + 57, marginY, marginX + 57, marginY + 33);

    // **Section 2: Report Title**
    doc.setFontSize(16).setFont("helvetica", "bold");
    doc.text(reportTitle, 105, marginY + 15, { align: "center" });

    // **Section 3: Right-Side Document Info**
    let rightX = marginX + 138;
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text(`Doc. No: ${docNo}`, rightX, marginY + 5);
    doc.line(marginX + 135, marginY + 8, contentWidth + 10, marginY + 8);
    doc.text(`Origin Date: ${OriginDate}`, rightX, marginY + 13);
    doc.line(marginX + 135, marginY + 16, contentWidth + 10, marginY + 16);
    doc.text(`Rev No.: ${revNo}`, rightX, marginY + 21);
    doc.line(marginX + 135, marginY + 24, contentWidth + 10, marginY + 24);
    doc.text(`Rev Date: ${revDate}`, rightX, marginY + 30);
    doc.line(marginX + 135, marginY + 33, contentWidth + 10, marginY + 33);
    doc.text(location, rightX, marginY + 39);
    doc.line(marginX + 135, marginY + 43, contentWidth + 10, marginY + 43);

    // **Vertical Line separating Document Info**
    doc.line(marginX + 135, marginY, marginX + 135, marginY + 60);

    // **Section 4: Trainer Details**
    doc.setFontSize(11).setFont("helvetica", "bold");
    doc.text("Trainer Name:", marginX + 2, marginY + 39);
    doc.text(trainerName || 'N/A', marginX + 50, marginY + 39);
    doc.line(marginX, marginY + 43, marginX + 135, marginY + 43);
    doc.text(`Total Trainings: ${trainingsData?.length || 0}`, marginX + 2, marginY + 50);
    doc.line(marginX, marginY + 53, marginX + 135, marginY + 53);
    doc.text(`Report Generated: ${dayjs().format("DD-MM-YYYY HH:mm")}`, marginX + 2, marginY + 58);
    doc.line(marginX, marginY + 60, contentWidth + 10, marginY + 60);

    // **Table Data**
    if (trainingsData && trainingsData.length > 0) {
      let currentStartY = 75;

      const pageWidth = doc.internal.pageSize.getWidth();
      const leftMargin = 10;
      const rightMargin = 10;
      const availableWidth = pageWidth - leftMargin - rightMargin;

      // Define column widths
      const desiredWidths = {
        0: 12,   // Sr No
        1: 45,   // Training Title
        2: 50,   // Skills
        3: 22,   // Start Date
        4: 22,   // End Date
        5: 28,   // Training Status
      };

      const totalDesiredWidth = Object.values(desiredWidths).reduce((a, b) => a + b, 0);
      const scaleFactor = availableWidth / totalDesiredWidth;

      const columnStyles = {};
      Object.entries(desiredWidths).forEach(([key, width]) => {
        const alignments = ['center', 'left', 'left', 'center', 'center', 'center'];
        columnStyles[key] = {
          halign: alignments[parseInt(key)],
          cellWidth: width * scaleFactor
        };
      });

      // Build table rows
      const allTableRows = trainingsData.map((training, index) => [
        (index + 1).toString(),
        training.trainingTitle || 'N/A',
        training.skillNames || 'No Skills',
        training.startTrainingDate || 'N/A',
        training.endTrainingDate || 'N/A',
        training.trainingStatus || 'N/A',
      ]);

      // Custom cell styling for status column
      const didDrawCell = (data) => {
        if (data.column.index === 5 && data.section === 'body') {
          const status = data.cell.text[0];
          if (status === 'Ongoing') {
            data.cell.styles.fillColor = [255, 250, 192]; // Light yellow
            data.cell.styles.textColor = [0, 0, 0];
            data.cell.styles.fontStyle = 'bold';
          } else if (status === 'Completed') {
            data.cell.styles.fillColor = [201, 252, 202]; // Light green
            data.cell.styles.textColor = [0, 100, 0];
            data.cell.styles.fontStyle = 'bold';
          } else if (status === 'Upcoming') {
            data.cell.styles.fillColor = [205, 233, 255]; // Light blue
            data.cell.styles.textColor = [0, 0, 139];
            data.cell.styles.fontStyle = 'bold';
          }
        }
      };

      doc.autoTable({
        startY: currentStartY,
        head: [["Sr No.", "Training Title", "Skills", "Start Date", "End Date", "Status"]],
        body: allTableRows,
        styles: {
          lineWidth: 0.1,
          lineColor: [0, 0, 0],
          fontSize: 9,
          textColor: [0, 0, 0],
          fontStyle: "normal",
          cellPadding: 4,
          valign: 'middle',
          halign: 'left',
          overflow: 'linebreak',
          minCellHeight: 12,
        },
        headStyles: {
          fillColor: [70, 130, 180],
          textColor: [255, 255, 255],
          fontStyle: "bold",
          fontSize: 10,
          halign: 'center',
          valign: 'middle',
          minCellHeight: 14,
        },
        alternateRowStyles: { fillColor: [245, 245, 245] },
        columnStyles: columnStyles,
        theme: "grid",
        margin: { left: leftMargin, right: rightMargin, top: 25, bottom: 20 },
        tableLineWidth: 0.1,
        tableWidth: availableWidth,
        willDrawPage: (data) => {
          if (data.pageNumber > 1) {
            doc.setFontSize(10).setFont("helvetica", "bold");
            doc.text(`${reportTitle} - Page ${data.pageNumber}`, pageWidth / 2, 12, { align: "center" });
            doc.setFontSize(9).setFont("helvetica", "normal");
            doc.text(`Trainer: ${trainerName}`, pageWidth / 2, 18, { align: "center" });
          }
        },
        didDrawCell: didDrawCell,
        rowPageBreak: 'avoid',
        showHead: 'everyPage',
      });

      // **Signatures Section**
      const finalY = doc.autoTable.previous.finalY;
      let signStartY = finalY + 20;
      const pageHeight = doc.internal.pageSize.getHeight();

      if (signStartY + 50 > pageHeight - 15) {
        doc.addPage();
        signStartY = 30;
      }

      doc.setFontSize(11).setFont("helvetica", "bold");
      doc.text("Sign of Trainer: ____________________", marginX + 5, signStartY);
      doc.text("Sign of HR: ____________________", marginX + 5, signStartY + 18);
      doc.text("Sign of HOD: ____________________", marginX + 5, signStartY + 36);
    } else {
      doc.setFontSize(12).setFont("helvetica", "normal");
      doc.text("No training records found for this trainer.", 105, 90, { align: "center" });
    }

    return doc;
  };

  const generatePDF = () => {
    const doc = createDoc();
    const pdfData = doc.output('datauristring');
    setPdfDataUrl(pdfData);
    setLoading(false);
    setPreviewOpen(true);
  };

  const handleClosePreview = () => {
    setPreviewOpen(false);
    setPdfDataUrl(null);
    if (onClose) {
      onClose();
    }
  };

  const handleDownloadPDF = () => {
    const doc = createDoc();
    doc.save(`Trainer_Report_${trainerName}_${dayjs().format('DD_MM_YYYY')}.pdf`);
  };

  return (
    <div>
      <Modal
        open={previewOpen}
        onClose={handleClosePreview}
        aria-labelledby="pdf-preview-title"
        aria-describedby="pdf-preview-description"
      >
        <Box sx={{ width: "85%", margin: "auto", mt: 5, backgroundColor: "white", padding: 2, borderRadius: 2 }}>
          <Typography variant="h6" sx={{ mb: 1 }}>
            Trainer Report Preview
          </Typography>

          {pdfDataUrl ? (
            <iframe
              src={pdfDataUrl}
              width="100%"
              height="500px"
              style={{ border: 'none' }}
              title="PDF Preview"
            />
          ) : (
            <Typography variant="body1">Loading PDF preview...</Typography>
          )}

          <div style={{ marginTop: '20px', display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
            <Button
              onClick={handleDownloadPDF}
              variant="contained"
              color="primary"
            >
              Download PDF
            </Button>
            <Button
              onClick={handleClosePreview}
              variant="outlined"
              color="secondary"
            >
              Close Preview
            </Button>
          </div>
        </Box>
      </Modal>
    </div>
  );
};

export default TrainerReportGenerator;
